services:
  elasticsearch:
    image: elasticsearch:8.15.3
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      #- '9300:9300'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
volumes:
  elasticsearch-data: